databases:
  - name: theelectrabazzar_db
    plan: free
    databaseName: theelectrabazzar_db
    user: theelectrabazzar_db

services:
  - type: web
    plan: free
    name: theElectraBazzar
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn theElectraBazzar.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: theelectrabazzar_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
