# Generated by Django 4.2.6 on 2024-03-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_createddate_cart_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_date',
            new_name='createdDate',
        ),
    ]
