# Generated by Django 5.0.3 on 2024-03-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_billingadress_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingadress',
            old_name='pin_code',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
