# Generated by Django 5.0.3 on 2024-03-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_pin_code_billingadress_pincode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAdress',
            new_name='BillingAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='createdDate',
        ),
    ]
