# Generated by Django 5.0.3 on 2024-03-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_billingadress_billingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
