# Generated by Django 5.0.3 on 2024-03-12 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_billlinggaddress_order_billingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oderId',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
