# Generated by Django 5.0.3 on 2024-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_order_oderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oderId',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(default=176397749175449081168548357902712370610, editable=False, unique=True),
        ),
    ]
