# Generated by Django 5.0.3 on 2024-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_order_oderid_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.BigIntegerField(default=64650908435720851835171750103553761157, editable=False, unique=True),
        ),
    ]
