# Generated by Django 5.0.3 on 2024-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_order_order_id_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.BigIntegerField(default=76592344378191992358583160822935678706, editable=False, unique=True),
        ),
    ]
